services:
  db:
    image: postgres:16
    container_name: veriproof-db
    environment:
      POSTGRES_DB: veriproof
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oracle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: veriproof-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
